spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

flyway:
  locations: classpath:db/migration,filesystem:run
  migrate: true
